const images = [
  { id: "1", link: "https://i.ibb.co/p0W4Bd5/KLG-Class-Sampanna-Karina-2.jpg" },
  // { id: "2", link: "https://i.ibb.co/TmsvVCq/foto2.png" },
  { id: "3", link: "https://i.ibb.co/zGrSvWz/foto3.png" },
  { id: "4", link: "https://i.ibb.co/mJKKStS/foto4.png" },
  { id: "5", link: "https://i.ibb.co/V9GfCNK/foto5.png" },
  { id: "6", link: "https://i.ibb.co/Gnj85zr/foto6.png" },
  { id: "7", link: "https://i.ibb.co/hfhFgRg/Karina.jpg" },
  { id: "8", link: "https://i.ibb.co/tLkFG1d/foto8.png" },
  { id: "9", link: "https://i.ibb.co/kQ3mPPV/foto9.png" },
  { id: "10", link: "https://i.ibb.co/StPKNt3/foto10.png" },
  { id: "11", link: "https://i.ibb.co/w7vGHS5/foto11.png" },
  { id: "12", link: "https://i.ibb.co/JnXY73c/foto12.png" },
  { id: "13", link: "https://i.ibb.co/stY6wF2/foto13.png" },
  { id: "14", link: "https://i.ibb.co/L93FNhZ/foto14.png" },
  { id: "15", link: "https://i.ibb.co/gTy0ZTp/foto15.png" },
  { id: "16", link: "https://i.ibb.co/xFXgb0F/foto16.png" },
  { id: "17", link: "https://i.ibb.co/D7RKWmR/foto17.png" },
  { id: "18", link: "https://i.ibb.co/mBxdfsJ/foto18.png" },
  { id: "19", link: "https://i.ibb.co/7vHCYgZ/foto19.png" },
  { id: "20", link: "https://i.ibb.co/gz86m3k/foto20.png" },
  { id: "21", link: "https://i.ibb.co/Ch3rg1G/foto21.png" },
  { id: "22", link: "https://i.ibb.co/Ch3rg1G/foto21.png" },
  { id: "23", link: "https://i.ibb.co/Ph26Hr2/foto22.png" },
  { id: "24", link: "https://i.ibb.co/Vj9HhXQ/foto24.png" },
  { id: "25", link: "https://i.ibb.co/pWL9W5q/foto25.png" },
  { id: "26", link: "https://i.ibb.co/WtfGyZq/foto26.jpg" },
  { id: "27", link: "https://i.ibb.co/5RMy9QW/foto27.jpg" },
  { id: "28", link: "https://i.ibb.co/FgXdFNz/foto28.jpg" },
  { id: "29", link: "https://i.ibb.co/w67CHpH/foto29.jpg" },
  { id: "30", link: "https://i.ibb.co/ynrpXx7/foto30.jpg" },
  { id: "31", link: "https://i.ibb.co/n6Fp83b/foto31.jpg" },
  { id: "32", link: "https://i.ibb.co/PghpS26/foto32.jpg" },
  { id: "33", link: "https://i.ibb.co/g33j8kk/foto33.jpg" },
  { id: "34", link: "https://i.ibb.co/wyn0P11/foto34.jpg" },
  { id: "35", link: "https://i.ibb.co/LpRmFhX/foto35.jpg" },
  { id: "36", link: "https://i.ibb.co/xJF5zxr/foto36.jpg" },
  { id: "37", link: "https://i.ibb.co/s3WFccb/foto37.jpg" },
  { id: "38", link: "https://i.ibb.co/yhfZXFH/foto38.jpg" },
  { id: "39", link: "https://i.ibb.co/vkMfdGF/foto39.jpg" },
  { id: "40", link: "https://i.ibb.co/ZcGN5c5/foto40.jpg" },
  { id: "41", link: "https://i.ibb.co/h8KkDvC/foto41.jpg" },
  { id: "42", link: "https://i.ibb.co/YR7MNXT/foto42.jpg" },
  { id: "43", link: "https://i.ibb.co/GRNybPv/foto43.jpg" },
  { id: "44", link: "https://i.ibb.co/922DMT2/foto44.jpg" },
  { id: "45", link: "https://i.ibb.co/mBgk9Ff/foto45.jpg" },
  { id: "46", link: "https://i.ibb.co/ZxFFxKk/foto61.png" },
  { id: "47", link: "https://i.ibb.co/GdpXHbT/foto47.jpg" },
  { id: "48", link: "https://i.ibb.co/tY4f9r3/foto48.jpg" },
  { id: "49", link: "https://i.ibb.co/PzgLdVv/foto49.jpg" },
  { id: "50", link: "https://i.ibb.co/m49ppXW/foto50.jpg" },
  { id: "51", link: "https://i.ibb.co/HPP9bQ6/foto51.jpg" },
  { id: "52", link: "https://i.ibb.co/tZtq3DM/Kusal-Karuna-Kristina.jpg" },
  { id: "53", link: "https://i.ibb.co/cr062mk/foto62.png" },
  { id: "54", link: "https://i.ibb.co/F3BLN6b/foto54.jpg" },
  // { id: "55", link: "" },
  { id: "56", link: "https://i.ibb.co/S50TV3f/foto56.png" },
  { id: "57", link: "https://i.ibb.co/Cw7xNGg/foto57.png" },
  { id: "58", link: "https://i.ibb.co/7W64Pwf/foto58.png" },
  { id: "59", link: "https://i.ibb.co/JRPKWwz/foto59.png" },
  { id: "60", link: "https://i.ibb.co/qs1psSN/foto60.png" },
];

export default images ;
